baseURL = 'https://blog.dasagho.com'
languageCode = 'en-us'
title = "David's Blog"
theme = 'hello-friends'

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
  [languages]
     [languages.en]
       title = "David's Blog"
       [languages.en.params.logo]
         logoText = "David's Blog"

