baseURL = 'https://blog.dasagho.com'
languageCode = 'en-us'
title = "David's Blog"
theme = 'hello-friends'

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
  title = "David's Blog"
