baseURL = 'https://pepe05422.github.io/blog/'
languageCode = 'en-us'
title = "David's Blog"
theme = 'hello-friend'

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false