name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - master  # Se ejecuta solo en la rama master

env:
  HUGO_VERSION: '0.121.2'  # Define aquí la versión de Hugo

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Usa Ubuntu 22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Utiliza la versión 4 de checkout

    - name: Setup Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        sudo dpkg -i hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb

    - name: Build
      run: hugo  # Compila el sitio con Hugo
    - name: List public directory
      run: ls -l public

    - name: Deploy
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages
        find . -maxdepth 1 ! -name 'public' ! -name '.git' ! -name '.' -exec rm -rf {} \;
        mv public/* .
        rm -rf public
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages --force
        git checkout master  # Vuelve a la rama master
        git branch -D gh-pages  # Elimina la rama temporal
